name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '18.17'
          cache: 'pnpm'

      - run: npm install -g pnpm

      - run: pnpm install

      - run: npm install -g @lhci/cli@0.6.x

      - run: pnpm run build

      # Run Lighthouse using Chromium in headless mode
      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
